'use client';
import {useEffect,useState} from 'react';
import type {TradePlan} from '@/lib/trade-plan';
type Item={market:'KR'|'US';symbol:string;name:string;exchange?:'ND'|'NY'|'NA'};
type Candidate=Item&{plan:TradePlan;price:number;distance:number|null;source:string;steps:{timeframe:string;state:string;detail:string}[]};
type Report={market:string;date?:string;closeAt?:string;generatedAt?:string;status:string;screened?:number;analyzed?:number;stale?:number;candidates:Candidate[];universe:Item[];errors?:{symbol:string;reason:string}[]};
export function CandidatesPanel({onOpen}:{onOpen:(item:Item)=>void}){
 const [market,setMarket]=useState<'KR'|'US'>('KR'),[report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(false);
 useEffect(()=>{const ac=new AbortController();setLoading(true);setError('');setReport(null);fetch(`/api/candidates?market=${market}`,{signal:ac.signal}).then(async r=>{const d=await r.json() as Report & {error?:string};if(!r.ok)throw new Error(d.error||'리포트 조회 실패');setReport(d);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!ac.signal.aborted)setLoading(false);});return()=>ac.abort();},[market,refresh]);
 const format=(n?:number)=>n===undefined?'미확정':`${market==='KR'?'₩':'$'}${n.toLocaleString('ko-KR',{maximumFractionDigits:market==='KR'?0:2})}`;
 const range=(p?:[number,number])=>p?`${format(p[0])} – ${format(p[1])}`:'조건 확인 후 확정';
 const statuses:Record<string,string>={pending:'첫 본장 마감 리포트 대기',complete:'분석 완료',partial:'일부 종목 분석 미완료',no_session:'휴장 또는 당일 데이터 미확인',resource_paused:'서버 자원 보호로 검색 보류',failed:'검색 실패'};
 return <section className="candidate-page"><header className="candidate-heading"><div><small>AFTER CLOSE · 조건 기반 종목 탐색</small><h2>오늘의 후보</h2><p>상위 구조로 계획하고, 작은 봉으로 진입을 확인합니다.</p></div><div className="candidate-actions"><button aria-pressed={market==='KR'} onClick={()=>setMarket('KR')}>한국</button><button aria-pressed={market==='US'} onClick={()=>setMarket('US')}>미국</button><button disabled={loading} onClick={()=>setRefresh(n=>n+1)}>리포트 새로고침</button></div></header>
 <div className="candidate-notice">{market==='KR'?'본장 15:30(KST)':'본장 16:00(뉴욕 현지 시각·서머타임 자동 반영)'} 마감 10분 후 검색 시작 · 미국 조기 폐장은 별도 적용. 고정 20종목 중 최대 6종목 정밀 분석. 새로고침은 저장된 결과만 읽습니다.</div>
 {loading&&<p role="status">저장된 리포트를 불러오고 있습니다.</p>}{error&&<p role="alert">{error}</p>}
 {report&&<><div className="candidate-summary"><strong>{statuses[report.status]||report.status}</strong><span>{report.date||'다음 본장 마감 후 생성'} · 선별 {report.screened||0}/20 · 정밀 분석 {report.analyzed||0}/6 · 후보 {report.candidates.length}개</span></div><p className="candidate-note">{report.generatedAt&&`작성 ${new Date(report.generatedAt).toLocaleString('ko-KR')} · `}마감 당시의 참고 계획입니다. 지금 진입하라는 신호가 아니며 다음 거래일에 가격·구조를 다시 확인해야 합니다. 숏 후보는 하락 관찰용이며 공매도 가능 여부를 확인하지 않습니다.</p>
 {!report.candidates.length&&<div className="candidate-empty">{report.status==='complete'?'이번 검색 범위에서 조건에 맞는 후보가 없습니다.':'아직 표시할 검증된 후보가 없습니다.'}<p>조건을 낮추거나 미확정 가격을 만들어 추천하지 않습니다.</p></div>}
 <div className="candidate-grid">{report.candidates.map(c=><article className="candidate-card" key={c.symbol}><div className="candidate-card-heading"><div><small>{c.symbol}</small><h3>{c.name}</h3></div><b className={c.plan.direction==='LONG'?'candidate-long':'candidate-short'}>{c.plan.direction==='LONG'?'롱 대기':'숏 관찰'}</b></div><p>{c.plan.ready?'마감 당시 참고 조건 충족 · 다음 장 재확인':c.plan.stage}</p><dl><div><dt>4H 관심 구역</dt><dd>{range(c.plan.interest)}</dd></div><div><dt>정밀 진입 후보</dt><dd>{range(c.plan.entry||c.plan.candidate?.entry)}</dd></div><div><dt>15분 상위 구조 손절</dt><dd>{format(c.plan.stop??c.plan.candidate?.stop)}</dd></div><div><dt>4H 스윙 목표</dt><dd>{format(c.plan.target??c.plan.candidate?.target)}</dd></div></dl><details><summary>선정 이유 · 아직 기다리는 조건</summary><p>{c.plan.context}</p>{c.steps.map(s=><p key={s.timeframe}><b>{s.timeframe}</b> {s.detail}</p>)}{c.plan.blockers?.map((b,i)=><p key={i}>• {b}</p>)}<small>{c.source} · 공통 거래 계획 엔진 · 손익비는 수익 확률이 아닙니다.</small></details><button onClick={()=>onOpen(c)}>현재 차트에서 다시 확인 ↗</button></article>)}</div>
 <details className="candidate-notice"><summary>검색 범위와 무료 서버 보호 기준</summary><p>일봉 방향이 확인된 종목을 최근 20일 거래대금 순으로 최대 6개 정밀 분석합니다. 후보 정렬은 마감 당시 조건 충족 여부, 관심 구역과의 거리 순입니다. 전 종목 검색이나 수익률 순위가 아닙니다.</p><p>동시 실행 1개 · CPU 10% · 메모리 최대 96MB · 실행 최대 15분 · 결과 28회/8MB 상한. 자원 부족 시 검색 보류, 하루 최대 3회 시도. 신규 유료 서버·스토리지는 생성하지 않습니다.</p><p>{report.universe.map(i=>i.name).join(' · ')}</p><p>차트는 현재 시세를 열기 때문에 이 리포트의 마감 가격과 다를 수 있습니다.</p></details>
 {!!report.errors?.length&&<details className="candidate-notice"><summary>미완료 종목 {report.errors.length}건</summary>{report.errors.map((e,i)=><p key={i}>{e.symbol}: {e.reason}</p>)}</details>}</>}
 </section>;
}
