'use client';
import {useEffect,useState} from 'react';
import {Gauge} from 'lucide-react';
import type {TradePlan} from '@/lib/trade-plan';
type Item={market:'KR'|'US';symbol:string;name:string;exchange?:'ND'|'NY'|'NA'};
type Candidate=Item&{selection?:string;evidence?:{volumeRatio:number;elevatedDays:number;return5:number;return20:number};tracking?:{status:string;firstSeen:string;history:{date:string;stage:string;direction:string;ready:boolean}[]};plan:TradePlan;price:number;distance:number|null;source:string;steps:{timeframe:string;state:string;detail:string}[]};
type Resources={state:'headroom'|'caution'|'protected'|'unknown';samples:number;minAvailableMiB:number|null;minFreeGiB:number|null;maxLoad:number;elapsedMs:number;cpuMs:number;requests:number;failedRequests:number;maxRequestMs:number;protectedEarlier:boolean};
type Report={scopeCount?:number;limits?:{universe:number};resources?:Resources;resourceHistory?:{date:string;scopeCount:number;state:Resources['state'];minAvailableMiB:number|null;maxLoad:number;elapsedMs:number}[];version?:number;previousCandidates?:{symbol:string;name:string;status:string;previousDate:string}[];market:string;date?:string;closeAt?:string;generatedAt?:string;status:string;screened?:number;analyzed?:number;stale?:number;candidates:Candidate[];universe:Item[];errors?:{symbol:string;reason:string}[]};
export function CandidatesPanel({onOpen}:{onOpen:(item:Item)=>void}){
 const [market,setMarket]=useState<'KR'|'US'>('KR'),[report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(false);
 useEffect(()=>{const ac=new AbortController();setLoading(true);setError('');setReport(null);fetch(`/api/candidates?market=${market}`,{signal:ac.signal}).then(async r=>{const d=await r.json() as Report & {error?:string};if(!r.ok)throw new Error(d.error||'리포트 조회 실패');setReport(d);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!ac.signal.aborted)setLoading(false);});return()=>ac.abort();},[market,refresh]);
 const format=(n?:number)=>n===undefined?'미확정':`${market==='KR'?'₩':'$'}${n.toLocaleString('ko-KR',{maximumFractionDigits:market==='KR'?0:2})}`;
 const range=(p?:[number,number])=>p?`${format(p[0])} – ${format(p[1])}`:'조건 확인 후 확정';
 const resourceLabels={headroom:'여유 관측',caution:'주의 · 확대 보류',protected:'자원 보호 작동',unknown:'측정 없음'};
 const statuses:Record<string,string>={pending:'첫 본장 마감 리포트 대기',complete:'분석 완료',partial:'일부 종목 분석 미완료',no_session:'휴장 또는 당일 데이터 미확인',resource_paused:'서버 자원 보호로 검색 보류',failed:'검색 실패'};
 const renderCandidates=(candidates:Candidate[])=>(<div className="candidate-grid">{candidates.map(c=><article className="candidate-card" key={c.symbol}><div className="candidate-card-heading"><div><small>{c.symbol}</small><h3>{c.name}</h3></div><b className={c.plan.direction==='LONG'?'candidate-long':'candidate-short'}>{c.plan.direction==='LONG'?'롱 대기':'숏 관찰'}</b></div><p>{c.selection==='interest'?'여러 날 관심 증가':c.selection==='liquidity'?'유동성 중심':'기존 선별'}{c.tracking&&` · ${c.tracking.status} · 최초 ${c.tracking.firstSeen}`}</p>{c.evidence&&<p>최근 5일 평균 거래량 {c.evidence.volumeRatio.toFixed(2)}배 · 평소보다 거래 증가 {c.evidence.elevatedDays}/5일 · 20거래일 가격 변화 {(c.evidence.return20*100).toFixed(1)}%</p>}<p>{c.plan.ready?'마감 당시 참고 조건 충족 · 다음 장 재확인':c.plan.stage}</p><dl><div><dt>4H 관심 구역</dt><dd>{range(c.plan.interest)}</dd></div><div><dt>정밀 진입 후보</dt><dd>{range(c.plan.entry||c.plan.candidate?.entry)}</dd></div><div><dt>15분 상위 구조 손절</dt><dd>{format(c.plan.stop??c.plan.candidate?.stop)}</dd></div><div><dt>4H 스윙 목표</dt><dd>{format(c.plan.target??c.plan.candidate?.target)}</dd></div></dl><details><summary>선정 이유 · 아직 기다리는 조건</summary><p>{c.plan.context}</p>{c.tracking&&<><p>최근 기록 (최대 5회, 관찰일 기준)</p>{c.tracking.history.map(h=><p key={h.date}>{h.date} · {h.direction==='LONG'?'롱':'숏'} · {h.ready?'참고 조건 충족':h.stage}</p>)}</>}{c.steps.map(s=><p key={s.timeframe}><b>{s.timeframe}</b> {s.detail}</p>)}{c.plan.blockers?.map((b,i)=><p key={i}>• {b}</p>)}<small>{c.source} · 공통 거래 계획 엔진 · 손익비는 수익 확률이 아닙니다.</small></details><button onClick={()=>onOpen(c)}>현재 차트에서 다시 확인 ↗</button></article>)}</div>);
 const [history,setHistory]=useState<{date:string;status:string;count:number;candidates:Item[]}[]>([]),[historyError,setHistoryError]=useState(''),[historyLoading,setHistoryLoading]=useState(false);
 const [archives,setArchives]=useState<Record<string,Report>>({}),[archiveErrors,setArchiveErrors]=useState<Record<string,string>>({});
 useEffect(()=>{const ac=new AbortController();setHistory([]);setArchives({});setArchiveErrors({});setHistoryError('');setHistoryLoading(true);fetch('/api/candidates?market='+market+'&history=1',{signal:ac.signal}).then(async r=>{const d=await r.json() as {reports:typeof history;unavailable?:number;error?:string};if(!r.ok||!Array.isArray(d.reports))throw new Error(d.error||'과거 기록을 불러오지 못했습니다.');setHistory(d.reports);if(d.unavailable)setHistoryError(d.unavailable+'개 기록은 읽지 못했습니다.');}).catch(e=>{if(e.name!=='AbortError')setHistoryError(e.message);}).finally(()=>{if(!ac.signal.aborted)setHistoryLoading(false);});return()=>ac.abort();},[market,refresh]);
 const loadArchive=async(date:string)=>{const key=market+date;if(archives[key])return;try{const r=await fetch('/api/candidates?market='+market+'&date='+encodeURIComponent(date));const d=await r.json() as Report & {error?:string};if(!r.ok)throw new Error(d.error||'조회 실패');setArchives(v=>({...v,[key]:d}));setArchiveErrors(v=>{const next={...v};delete next[key];return next;});}catch(e){setArchiveErrors(v=>({...v,[key]:e instanceof Error?e.message:'조회 실패'}));}};
 return <section className="candidate-page"><header className="candidate-heading"><div><small>AFTER CLOSE · 조건 기반 종목 탐색</small><h2>오늘의 후보</h2><p>상위 구조로 계획하고, 작은 봉으로 진입을 확인합니다.</p></div><div className="candidate-actions"><button aria-pressed={market==='KR'} onClick={()=>setMarket('KR')}>한국</button><button aria-pressed={market==='US'} onClick={()=>setMarket('US')}>미국</button><button disabled={loading} onClick={()=>setRefresh(n=>n+1)}>리포트 새로고침</button></div></header>
 <div className="candidate-notice">{market==='KR'?'본장 15:30(KST)':'본장 16:00(뉴욕 현지 시각·서머타임 자동 반영)'} 마감 10분 후 검색 시작 · 미국 조기 폐장은 별도 적용. 매일 고정 {report?.limits?.universe??25}종목의 일봉 확인 · 최대 6종목 정밀 분석. 새로고침은 저장된 결과만 읽습니다.</div>

 <section className="candidate-history" aria-label="과거 후보 타임라인"><header><h3>지난 후보 타임라인</h3><span>날짜를 눌러 당시 후보 펼치기</span></header><p>한국·미국 합산 최근 28회분을 저장합니다. 보관 한도가 지나면 오래된 기록부터 삭제됩니다. 아래 가격은 당시 기록이며 현재 진입 신호가 아닙니다.</p>
 {historyLoading&&<p role="status">과거 기록을 불러오는 중입니다.</p>}{historyError&&<p role="alert">{historyError}</p>}{!historyLoading&&!historyError&&!history.length&&<p>아직 저장된 과거 기록이 없습니다.</p>}
 {history.map(h=><details key={market+h.date} className="candidate-history-day" onToggle={e=>{if(e.currentTarget.open)void loadArchive(h.date);}}><summary><strong>{h.date}</strong><span>{statuses[h.status]||h.status} · 후보 {h.count}개</span><span className="candidate-history-names">{h.candidates.map(c=>c.name).join(' · ')||'선정 후보 없음'}</span></summary><div className="candidate-history-body"><p>마감 당시 저장된 계획 · {archives[market+h.date]?.generatedAt?new Date(archives[market+h.date].generatedAt!).toLocaleString('ko-KR'):h.date}</p>{archiveErrors[market+h.date]?<p role="alert">{archiveErrors[market+h.date]} <button onClick={()=>void loadArchive(h.date)}>다시 시도</button></p>:archives[market+h.date]?<>{!archives[market+h.date].candidates.length&&<p>이 기록에는 선정된 후보가 없습니다. ({statuses[h.status]||h.status})</p>}{renderCandidates(archives[market+h.date].candidates)}</>:<p role="status">당시 후보를 불러오고 있습니다.</p>}</div></details>)}
 </section>
 {loading&&<p role="status">저장된 리포트를 불러오고 있습니다.</p>}{error&&<p role="alert">{error}</p>}
 {report&&<><details className={`candidate-resource candidate-resource-${report.resources?.state||'unknown'}`}><summary><Gauge size={18}/><strong>검색 당시 서버: {resourceLabels[report.resources?.state||'unknown']}</strong><span>상세 보기</span></summary><div>{report.resources?<><p>측정 대상: {report.date} 검색 · {report.resources.samples}개 요청 전 표본. 실시간 상태나 순간 최대 사용량은 아닙니다.</p><p>실행 {(report.resources.elapsedMs/1000).toFixed(1)}초 · 최저 가용 메모리 {report.resources.minAvailableMiB?.toFixed(0)??'미측정'}MiB · 최대 시스템 부하 {report.resources.maxLoad.toFixed(2)} · 최저 디스크 여유 {report.resources.minFreeGiB?.toFixed(1)??'미측정'}GiB</p><p>브리지 요청 {report.resources.requests}회 / 실패 {report.resources.failedRequests}회 · 가장 긴 응답 {(report.resources.maxRequestMs/1000).toFixed(1)}초 · 검색 프로세스 CPU 사용 {(report.resources.cpuMs/1000).toFixed(2)}초</p>{report.resources.protectedEarlier&&<p>같은 날 이전 시도에서 자원 보호가 작동했습니다. 이번 성공만으로 여유 상태로 바꾸지 않습니다.</p>}</>:<p>이 리포트에는 서버 측정 기록이 없습니다. 다음 예약 검색부터 기록합니다. 측정 없음은 정상 또는 여유를 의미하지 않습니다.</p>}<p>여유 관측: 전체 검색 완료, 가용 메모리 192MiB 이상, 시스템 부하 0.8 미만, 실행 10분 미만, 요청 실패 없음. 시스템 부하는 CPU 사용률이 아닙니다. 보호 제한은 메모리 128MiB·부하 1.5·디스크 2GiB 기준을 유지합니다.</p><p>최근 여러 본장 검색에서 여유가 지속되고 차트 응답에도 영향이 없는지 확인한 뒤 범위를 수동으로 늘립니다. 자동 확대하지 않습니다. 기존 검색에 함께 기록하며 별도 상태 조회를 반복하지 않습니다.</p>{report.resourceHistory?.map(h=><p key={h.date}>{h.date} · {h.scopeCount}종목 · {resourceLabels[h.state]} · {(h.elapsedMs/1000).toFixed(0)}초 · 가용 메모리 {h.minAvailableMiB?.toFixed(0)??'—'}MiB</p>)}</div></details><div className="candidate-summary"><strong>{statuses[report.status]||report.status}</strong><span>{report.date||'다음 본장 마감 후 생성'} · 선별 {report.screened||0}/{report.scopeCount??20} · 정밀 분석 {report.analyzed||0}/6 · 후보 {report.candidates.length}개</span></div><p className="candidate-note">{report.generatedAt&&`작성 ${new Date(report.generatedAt).toLocaleString('ko-KR')} · `}마감 당시의 참고 계획입니다. 지금 진입하라는 신호가 아니며 다음 거래일에 가격·구조를 다시 확인해야 합니다. 숏 후보는 하락 관찰용이며 공매도 가능 여부를 확인하지 않습니다.</p>
 {!report.candidates.length&&<div className="candidate-empty">{report.status==='complete'?'이번 검색 범위에서 조건에 맞는 후보가 없습니다.':'아직 표시할 검증된 후보가 없습니다.'}<p>조건을 낮추거나 미확정 가격을 만들어 추천하지 않습니다.</p></div>}
 {report.version!==2&&<p className="candidate-notice">이 결과는 이전 선별 기준으로 작성되었습니다. 여러 날 관심 증가·후보 변화는 다음 마감 검색부터 표시됩니다.</p>}
 {renderCandidates(report.candidates)}
 <details className="candidate-notice"><summary>검색 범위와 무료 서버 보호 기준</summary><p>유동성 중심 3자리와 관심 증가 최대 3자리를 나눕니다. 관심 증가 후보가 부족하면 유동성 후보로 채우되 총 6개를 넘지 않습니다. 관심 증가는 직전 20일 대비 최근 5일 평균 거래량 1.3배 이상, 5일 중 3일 이상 거래량 1.2배 이상, 20일 가격 상승과 평균가격 이상 여부로 탐색합니다. 후보 정렬은 마감 당시 조건 충족 여부, 관심 구역과의 거리 순입니다. 전 종목 검색이나 수익률 순위가 아닙니다.</p><p>20일 중앙 거래대금 최소 국장 10억원·미장 100만달러, 최근 5일 거래 지속성을 확인합니다. 하루 거래량 5배와 가격 변동 15%가 함께 나타나거나 5일 변동이 40% 이상이면 탐색에서 보류합니다. 이는 시험 적용하는 종목 탐색 기준이며 강의의 진입 규칙이 아닙니다. 밈주식 판별·재무 성장성·호가 간격은 검증하지 않습니다.</p><p>동시 실행 1개 · CPU 10% · 메모리 최대 96MB · 실행 최대 15분 · 결과 28회/8MB 상한. 자원 부족 시 검색 보류, 하루 최대 3회 시도. 신규 유료 서버·스토리지는 생성하지 않습니다.</p><p>{report.universe.map(i=>i.name).join(' · ')}</p><p>차트는 현재 시세를 열기 때문에 이 리포트의 마감 가격과 다를 수 있습니다.</p></details>
 {!!report.previousCandidates?.length&&<details className="candidate-notice"><summary>이전 후보의 변화 · {report.previousCandidates.length}종목</summary>{report.previousCandidates.map(c=><p key={c.symbol}>{c.name} ({c.symbol}) · {c.status} · 이전 관찰 {c.previousDate}</p>)}</details>}
 {!!report.errors?.length&&<details className="candidate-notice"><summary>미완료 종목 {report.errors.length}건</summary>{report.errors.map((e,i)=><p key={i}>{e.symbol}: {e.reason}</p>)}</details>}</>}
 </section>;
}
