'use client';
import {useState} from 'react';
import {reviewKinds,reviewEvidence,zoneDifference,validateReview,type ReviewDraft,type EntryReview} from '@/lib/entry-review';
import type {AutoState} from '@/lib/auto-paper';
import {DecisionReplayPanel} from './decision-replay';
type Run={id:string;config:{symbol:string;market:string};state:AutoState};
const blank:ReviewDraft={kind:'uncertain',expected:'UNSURE',frame:'1m',low:null,high:null,reference:'',notes:''};
const format=(at?:number)=>at?new Date(at).toLocaleString('ko-KR'):'미확인';
export function EntryReviewPanel(){
  const [runs,setRuns]=useState<Run[]>([]),[reviews,setReviews]=useState<EntryReview[]>([]),[selected,setSelected]=useState(''),[saved,setSaved]=useState<EntryReview|null>(null),[draft,setDraft]=useState<ReviewDraft>({...blank}),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all'),[chart,setChart]=useState(false),[loaded,setLoaded]=useState(false);
  const candidates=runs.flatMap(run=>(run.state.decisions||[]).map(d=>({run,d,key:`${run.id}:${d.at}`})));
  const candidate=candidates.find(c=>c.key===selected),d=saved?.decision||candidate?.d;
  const facts=d?reviewEvidence(d):null,diff=d?zoneDifference(d,draft):null;
  const eligible=candidates.filter(c=>filter==='all'||(filter==='entry'?reviewEvidence(c.d).entry:!reviewEvidence(c.d).entry));
  async function load(){setBusy(true);setError('');try{const [a,b]=await Promise.all([fetch('/api/paper/auto',{cache:'no-store'}),fetch('/api/paper/reviews',{cache:'no-store'})]);const p=await a.json() as {runs:Run[];error?:string},q=await b.json() as {reviews:EntryReview[];error?:string};if(!a.ok||!b.ok)throw new Error(p.error||q.error||'목록 불러오기 실패');setRuns(p.runs);setReviews(q.reviews);setLoaded(true);}catch(e){setError(e instanceof Error?e.message:'불러오기 실패');}finally{setBusy(false);}}
  function choose(key:string){setSelected(key);setSaved(null);setDraft({...blank});setChart(false);setMessage('');setError('');}
  async function save(){if(!d)return;setError('');setMessage('');try{validateReview(draft);}catch(e){setError((e as Error).message);return;}setBusy(true);try{const body=saved?{id:saved.id,revision:saved.revision,draft}:{runId:candidate!.run.id,at:d.at,draft};const r=await fetch('/api/paper/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const p=await r.json() as {reviews:EntryReview[];error?:string};if(!r.ok)throw new Error(p.error||'저장 실패');setReviews(p.reviews);const current=p.reviews.find(x=>x.runId===(saved?.runId||candidate?.run.id)&&x.at===d.at);if(current)setSaved(current);setMessage('검토와 당시 판단을 계정에 저장했습니다. 저장 차트가 있으면 함께 별도 보관됩니다.');}catch(e){setError(e instanceof Error?e.message:'저장 실패');}finally{setBusy(false);}}
  function download(){if(!d)return;const url=URL.createObjectURL(new Blob([JSON.stringify({schema:'entry-review-v1',decision:d,draft,computedEvidence:facts,zoneDifference:diff,classification:'reviewer-assessment'},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${d.symbol}-${d.at}-review.json`;a.click();URL.revokeObjectURL(url);}
  return <section className="lecture-casebook">
    <h2>진입·구역 차이 검토</h2><p>자동 판단의 사실과 검토자의 평가를 분리합니다. 거래가 없었다고 곧바로 ‘놓친 진입’으로 판정하지 않습니다. 그 시점에 알 수 있었던 구조와 가격만으로 기대 행동을 기록하세요.</p>
    <button disabled={busy} onClick={()=>void load()}>{busy?'처리 중…':'판단·저장 검토 불러오기'}</button>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
    <div className="casebook-columns"><article><h3>새 검토</h3><label>판단 필터<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체 판단</option><option value="entry">진입 체결 있음 · 성급한 진입 검토</option><option value="wait">진입 체결 없음 · 놓친 진입 검토</option></select></label><label>판단 선택<select disabled={busy} value={saved?'':selected} onChange={e=>choose(e.target.value)}><option value="">선택하세요</option>{eligible.map(c=><option key={c.key} value={c.key}>{c.run.config.market} {c.d.symbol} · {format(c.d.at)} · {c.d.reason}</option>)}</select></label>{loaded&&!candidates.length&&<p>자동 실험의 판단 기록이 쌓이면 선택할 수 있습니다.</p>}</article>
    <article><h3>저장한 검토 · 최근 100건</h3><label>저장 기록<select disabled={busy} value={saved?.id||''} onChange={e=>{const r=reviews.find(x=>x.id===e.target.value);if(r){setSaved(r);setDraft({...r.draft});setChart(false);setError('');setMessage('');}}}><option value="">선택하세요</option>{reviews.map(r=><option key={r.id} value={r.id}>{reviewKinds[r.draft.kind]} · {r.decision.symbol} · {format(r.at)}</option>)}</select></label><p>저장한 검토는 최근 200건의 자동 기록이 교체되어도 남습니다. 같은 판단은 저장 목록에서 수정합니다.</p></article></div>
    {d&&facts&&<><h3>{d.symbol} · {format(d.at)}</h3><p>모델 {d.model} · {d.stage} · {d.reason}</p>
      <div className="casebook-columns"><article><h3>프로그램이 남긴 사실</h3><p>이 판단의 진입 체결: {facts.entry?'있음':'없음'} · 기존 보유: {d.position?`${d.position.quantity}주`:'없음'}</p><p>접촉·전환·재접촉 시각 순서: {facts.sequence===null?'필요한 기록 부족':facts.sequence?'기록된 순서 충족':'순서 불일치 확인 필요'}</p><p>H4 접촉 {format(d.setup?.touch)}<br/>M15 확정 {format(d.setup?.m15?.at)}<br/>M15 재접촉 {format(d.setup?.retest)}<br/>M1 확정 {format(d.setup?.m1?.at)}</p><p>관측가 {d.price??'없음'} · 1분 구역 안 {facts.inside===null?'미확인':facts.inside?'예':'아니오'} · 후보 가중 목표 {facts.rr===null?'미확인':`${facts.rr.toFixed(2)}R`}</p>{facts.blocked.map(x=><p key={x}>데이터 차단: {x}</p>)}<p>이 사실 요약만으로 강의와의 일치나 정답 진입을 확정하지 않습니다.</p></article>
      <article><h3>검토자의 기대 행동</h3><label>분류<select value={draft.kind} onChange={e=>setDraft(v=>({...v,kind:e.target.value as ReviewDraft['kind']}))}>{Object.entries(reviewKinds).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>그 시점에 기대한 행동<select value={draft.expected} onChange={e=>setDraft(v=>({...v,expected:e.target.value as ReviewDraft['expected']}))}><option value="UNSURE">판단 보류</option><option value="ENTER">진입했어야 함</option><option value="WAIT">기다렸어야 함</option></select></label><p>{draft.kind==='early'&&!facts.entry?'이 판단에는 신규 진입 체결이 없습니다. 실제 진입 기록을 선택했는지 확인하세요.':draft.kind==='missed'&&facts.entry?'이 판단에는 진입 체결이 있습니다. 비교하려는 누락 시점을 확인하세요.':''}</p></article></div>
      <h3>구역 선택 비교</h3><div className="casebook-columns"><label>구역 시간대<select value={draft.frame} onChange={e=>setDraft(v=>({...v,frame:e.target.value as ReviewDraft['frame']}))}>{['4H','15m','1m'].map(f=><option key={f}>{f}</option>)}</select></label><div><label>기대 하단<input type="number" step="any" value={draft.low??''} onChange={e=>setDraft(v=>({...v,low:e.target.value===''?null:Number(e.target.value)}))}/></label><label>기대 상단<input type="number" step="any" value={draft.high??''} onChange={e=>setDraft(v=>({...v,high:e.target.value===''?null:Number(e.target.value)}))}/></label></div></div>
      {diff?<p>실제 구역 {diff.actual.low}–{diff.actual.high} · 기대−실제 하단 {diff.lowDelta.toFixed(3)} / 상단 {diff.highDelta.toFixed(3)} · 교집합÷합집합 구간 겹침 {diff.overlapPct.toFixed(1)}%</p>:<p>선택 시간대의 실제 구역과 유효한 기대 구역이 있어야 가격 차이를 계산할 수 있습니다.</p>}
      <label>강의 근거 (강의 번호·영상 시각 등)<input maxLength={500} value={draft.reference} onChange={e=>setDraft(v=>({...v,reference:e.target.value}))}/></label>
      <label>판정 이유·차이·후속 확인 (필수)<textarea maxLength={5000} value={draft.notes} onChange={e=>setDraft(v=>({...v,notes:e.target.value}))} placeholder="당시 어떤 구조를 보고 진입 또는 대기를 기대했는지 기록하세요. 이후 가격 상승·하락만으로 판단하지 마세요."/></label>
      <div className="auto-paper-controls"><button disabled={busy} onClick={()=>void save()}>{saved?'검토 수정 저장':'판단·검토 저장'}</button><button onClick={download}>현재 검토 내려받기</button>{(saved?.hasChart||(!saved&&d.replayKey))&&<button onClick={()=>setChart(p=>!p)}>{chart?'차트 닫기':'실제·기대 구역을 차트로 비교'}</button>}</div>
      <p>선택을 바꾸기 전에 저장하세요. 검토 결과는 사용자 평가이며 자동매매 규칙을 변경하지 않습니다.</p>
      {chart&&<DecisionReplayPanel runId={saved?.runId||candidate!.run.id} at={d.at} reviewId={saved?.id} onClose={()=>setChart(false)} expectedZone={draft.low!==null&&draft.high!==null&&draft.low>0&&draft.high>draft.low?{frame:draft.frame,low:draft.low,high:draft.high}:undefined}/>}
    </>}
  </section>;
}
