import test from 'node:test';
import assert from 'node:assert/strict';
import { advanceAuto,newAutoState,closedBars,validBars,entryTerms,qualifiedZone,shiftedZone } from './auto-paper.ts';
const now=Date.UTC(2026,8,10,12,0,30), minute=60000;
const config={market:'US',symbol:'TEST',exchange:'ND',capital:10000,riskPct:.5,feeBps:5,slippageBps:5};
function bars(rows,step=1,end=now-30000){return rows.map(([high,low,close],i)=>({date:new Date(end-(rows.length-1-i)*step*minute).toISOString(),open:(high+low)/2,high,low,close,volume:100}));}
const h4=bars([...Array(17).fill([10,8,9]),[12,9,11],[14,10,13],[13,11,12],[12,10,11]],240);
const h1=bars([...Array(17).fill([10,8,9]),[9.5,8,9],[12,9,11],[12,9,11],[12,9,11]],60);
function feed(){return {source:'Kiwoom REST API',symbol:'TEST',price:8.5,observedAt:now,timeframes:{'1m':bars(Array(25).fill([8.7,8.35,8.5])),'15m':bars(Array(25).fill([9,8.2,8.6]),15),'1H':h1,'4H':h4}};}
function ready(){const s=newAutoState(config,now-100*minute);const c=qualifiedZone(closedBars(h4,240,now),240);assert.ok(c);s.setup={id:c.zone.id,zone:c.zone,target:c.target,expires:now+86400000,touch:now-60*minute,m15:{low:8.1,high:8.9,at:now-40*minute,id:'m15'},retest:now-20*minute,m1:{low:8.3,high:8.7,at:now-2*minute,id:'m1'}};return s;}
test('native completed bars exclude unfinished/future candles',()=>{const a=bars(Array(25).fill([10,8,9]));assert.equal(closedBars(a,1,now).length,24);assert.ok(closedBars(a,1,now).every(b=>Date.parse(b.date)+minute<=now));});
test('invalid OHLC and unordered timestamps fail data validation',()=>{const a=feed().timeframes['1m'];assert.equal(validBars(a),true);a[1].low=20;assert.equal(validBars(a),false);assert.equal(validBars([...a].reverse()),false);});
test('costed risk sizing caps loss and available cash',()=>{const t=entryTerms(100,98,110,10000,config);assert.ok(t.quantity*t.unitRisk<=50);assert.ok(t.quantity*t.entry*1.0005<=10000);assert.ok(t.rr<5);assert.equal(entryTerms(100,101,110,10000,config).quantity,0);});
test('missing M1 never silently substitutes M5',()=>{const f=feed();delete f.timeframes['1m'];const s=advanceAuto(ready(),config,f,now);assert.equal(s.stage,'DATA_WAIT');assert.equal(s.fills.length,0);});
test('stale/wrong instrument/fallback source cannot fill',()=>{for(const edit of [{symbol:'OTHER'},{source:'Yahoo Finance'},{observedAt:now-31000}]){const s=advanceAuto(ready(),config,{...feed(),...edit},now);assert.equal(s.stage,'DATA_WAIT');assert.equal(s.fills.length,0);}});
test('fresh confirmed sequence opens one costed position; duplicate tick cannot reenter',()=>{const s=advanceAuto(ready(),config,feed(),now);assert.equal(s.fills.length,1);assert.equal(s.fills[0].side,'BUY');assert.ok(s.position.entry>8.5);assert.ok(s.position.stop<8.3);const again=advanceAuto(s,config,feed(),now);assert.equal(again.fills.length,1);assert.equal(again.cash,s.cash);});
test('opening does not act on pre-entry bar extrema',()=>{const s=advanceAuto(ready(),config,feed(),now);assert.ok(s.position);const f=feed();f.timeframes['1m'][0].low=1;const again=advanceAuto(s,config,f,now);assert.equal(again.fills.length,1);});
test('new entry paused, existing stop still exits',()=>{assert.equal(advanceAuto(ready(),config,feed(),now,false).fills.length,0);const s=advanceAuto(ready(),config,feed(),now);const f={...feed(),price:8,observedAt:now+1000};const closed=advanceAuto(s,config,f,now+1000,false);assert.equal(closed.fills.length,2);assert.equal(closed.closed,1);assert.ok(closed.netPnl<0);assert.ok(!closed.position);});
test('fees on both sides count in realized P&L and R',()=>{const s=advanceAuto(ready(),config,feed(),now);const f={...feed(),price:14,observedAt:now+1000};const closed=advanceAuto(s,config,f,now+1000);const buy=closed.fills[1],sell=closed.fills[0];assert.ok(Math.abs(sell.pnl-((sell.price-buy.price)*buy.quantity-buy.fee-sell.fee))<1e-8);assert.ok(Math.abs(closed.cash-config.capital-sell.pnl)<1e-8);assert.equal(advanceAuto(closed,config,f,now+1000).fills.length,2);});
test('same candle stop and target selects stop; gap uses worse open',()=>{const s=advanceAuto(ready(),config,feed(),now);const f=feed();const bar={date:new Date(now+30000).toISOString(),open:8,high:15,low:7,close:9,volume:100};f.timeframes['1m'].push(bar,{...bar,date:new Date(now+90000).toISOString()});f.observedAt=now+95000;const closed=advanceAuto(s,config,f,now+95000);assert.equal(closed.fills[0].side,'SELL');assert.equal(closed.fills[0].price,8*.9995);assert.ok(closed.netPnl<0);});
test('entry cannot use expired M1 event or a non-PP upper internal direction',()=>{const a=ready();a.setup.m1.at=now-31*minute;assert.equal(advanceAuto(a,config,feed(),now).stage,'EXPIRED');const f=feed();f.timeframes['1H']=bars(Array(25).fill([10,8,9]),60);assert.equal(advanceAuto(ready(),config,f,now).stage,'WAIT_PP');});
test('fresh setup waits for live H4 touch instead of replaying old entries',()=>{const s=advanceAuto(newAutoState(config,now),config,feed(),now);assert.equal(s.stage,'WAIT_M15_SHIFT');assert.equal(s.fills.length,0);assert.equal(s.setup.touch,now);});
test('raw structure shift must follow parent contact and be contained in parent',()=>{const a=bars([[10,8,9],[10,8,9],[9,6,7],[8,5,6],[7,5.5,6],[11,6,10.5]]);const z=shiftedZone(a,1,Date.parse(a[2].date),{low:4,high:12,at:0,id:'parent'});assert.ok(z);assert.equal(shiftedZone(a,1,now+2*minute,{low:4,high:12,at:0,id:'p'}),undefined);assert.equal(shiftedZone(a,1,0,{low:8,high:9,at:0,id:'p'}),undefined);});
test('a persisted prior fill blocks re-entry after setup reset/restart',()=>{const s=advanceAuto(ready(),config,feed(),now);const c=advanceAuto(s,config,{...feed(),price:14,observedAt:now+1000},now+1000);delete c.setup;const r=advanceAuto(c,config,feed(),now+2000);assert.equal(r.fills.length,2);assert.equal(r.stage,'WAIT_NEW_SETUP');});
