import test from 'node:test';
import assert from 'node:assert/strict';
import {historicalFeed,runAutoBacktest} from './auto-backtest.ts';
import {advanceAuto,newAutoState} from './auto-paper.ts';
const at=Date.UTC(2026,8,11,12),min=60000;
const config={market:'US',symbol:'TEST',exchange:'ND',capital:10000,riskPct:.5,feeBps:5,slippageBps:5};
const bars=(step)=>Array.from({length:35},(_,i)=>({date:new Date(at-(34-i)*step*min).toISOString(),open:10,high:11,low:9,close:10.5,volume:100}));
const input={symbol:'TEST',source:'Kiwoom REST API',timeframes:{'1m':bars(1),'15m':bars(15),'1H':bars(60),'4H':bars(240)}};
test('historical adapter hides future candles and unfinished OHLCV',()=>{const f=historicalFeed(input,at-2*min,10);const current=f.timeframes['1m'].at(-1);assert.equal(Date.parse(current.date),at-2*min);assert.deepEqual([current.high,current.low,current.close,current.volume],[10,10,10,0]);const changed=structuredClone(input);for(const rows of Object.values(changed.timeframes))for(const b of rows)if(Date.parse(b.date)>=at-2*min){b.high=999;b.close=998;}assert.deepEqual(historicalFeed(changed,at-2*min,10),f);});
test('backtest output equals sequential calls to the current production engine',async()=>{const r=await runAutoBacktest(input,config);let s=newAutoState(config,r.start);for(const b of input.timeframes['1m'].filter(b=>Date.parse(b.date)>=r.start)){const now=Date.parse(b.date);s=advanceAuto(s,config,historicalFeed(input,now,b.open),now);}assert.deepEqual(r.state,s);assert.equal(r.samples+r.skipped,35);assert.equal(r.end,at);});
test('missing native M1 and fallback data are rejected rather than substituted',async()=>{await assert.rejects(runAutoBacktest({...input,source:'Yahoo Finance'},config),/키움/);const broken=structuredClone(input);delete broken.timeframes['1m'];await assert.rejects(runAutoBacktest(broken,config),/1m/);});
