export type Candle={date:string;open:number;high:number;low:number;close:number;volume:number};
export type Pivot={index:number;price:number;kind:'high'|'low';label:string};
export type Snapshot={trend:string;sequence:string;event:string;score:number};
export type Analysis={score:number;bias:'LONG'|'SHORT'|'NEUTRAL';atr:number;pivots:Pivot[];poc:number;vah:number;val:number;hvn:number[];lvn:number[];profile:number[];profileStart:number;entry:[number,number];stop:number;target:number;rr:number;snapshots:Record<string,Snapshot>;confidence:number};
export type Backtest={trades:number;wins:number;winRate:number;returnPct:number;maxDrawdown:number;profitFactor:number;avgRR:number;equity:number[];buyHold:number};

const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
export function atr(data:Candle[],period=14){const tr=data.map((c,i)=>i?Math.max(c.high-c.low,Math.abs(c.high-data[i-1].close),Math.abs(c.low-data[i-1].close)):c.high-c.low);return avg(tr.slice(-period));}
export function pivots(data:Candle[],w=3){const out:Pivot[]=[];for(let i=w;i<data.length-w;i++){const slice=data.slice(i-w,i+w+1);if(data[i].high===Math.max(...slice.map(c=>c.high)))out.push({index:i,price:data[i].high,kind:'high',label:'H'});if(data[i].low===Math.min(...slice.map(c=>c.low)))out.push({index:i,price:data[i].low,kind:'low',label:'L'});}let ph:number|undefined,pl:number|undefined;for(const p of out){if(p.kind==='high'){p.label=ph===undefined?'H':p.price>ph?'HH':'LH';ph=p.price}else{p.label=pl===undefined?'L':p.price>pl?'HL':'LL';pl=p.price}}return out;}
export function resample(data:Candle[],size:number){const out:Candle[]=[];for(let i=0;i<data.length;i+=size){const g=data.slice(i,i+size);if(!g.length)continue;out.push({date:g.at(-1)!.date,open:g[0].open,high:Math.max(...g.map(c=>c.high)),low:Math.min(...g.map(c=>c.low)),close:g.at(-1)!.close,volume:g.reduce((s,c)=>s+c.volume,0)})}return out;}
function snap(data:Candle[]):Snapshot{const ps=pivots(data,Math.max(2,Math.min(4,Math.floor(data.length/20))));const last=ps.slice(-4),hi=last.filter(p=>p.kind==='high').at(-1),lo=last.filter(p=>p.kind==='low').at(-1),bull=last.filter(p=>p.label==='HH'||p.label==='HL').length,bear=last.filter(p=>p.label==='LH'||p.label==='LL').length,event=hi&&data.at(-1)!.close>hi.price?'External BOS ↑':lo&&data.at(-1)!.close<lo.price?'External BOS ↓':bull>=bear?'Internal structure ↑':'Internal structure ↓';return{trend:bull>bear?'BULLISH':bear>bull?'BEARISH':'TRANSITION',sequence:last.map(p=>p.label).join(' · ')||'판정 중',event,score:Math.round(50+Math.abs(bull-bear)*10)}}
export function analyze(data:Candle[]):Analysis{if(data.length<20)throw Error('분석에는 최소 20개 캔들이 필요합니다.');const last=data.at(-1)!.close,a=atr(data),ps=pivots(data),recent=ps.slice(-8),bull=recent.filter(p=>p.label==='HH'||p.label==='HL').length,bear=recent.filter(p=>p.label==='LH'||p.label==='LL').length,bias=bull>bear?'LONG':bear>bull?'SHORT':'NEUTRAL';const start=Math.max(0,(recent.find(p=>p.kind===(bias==='SHORT'?'high':'low'))?.index??data.length-80));const range=data.slice(start),min=Math.min(...range.map(c=>c.low)),max=Math.max(...range.map(c=>c.high)),bins=24,step=Math.max((max-min)/bins,.000001),profile=Array(bins).fill(0);for(const c of range){const typical=(c.high+c.low+c.close)/3,idx=Math.min(bins-1,Math.max(0,Math.floor((typical-min)/step)));profile[idx]+=c.volume}const total=profile.reduce((s,v)=>s+v,0),pocIdx=profile.indexOf(Math.max(...profile));let selected=new Set([pocIdx]),sum=profile[pocIdx],up=pocIdx+1,down=pocIdx-1;while(sum<total*.7&&(down>=0||up<bins)){const uv=up<bins?profile[up]:-1,dv=down>=0?profile[down]:-1;if(uv>=dv){selected.add(up);sum+=uv;up++}else{selected.add(down);sum+=dv;down--}}const ids=[...selected],val=min+Math.min(...ids)*step,vah=min+(Math.max(...ids)+1)*step,poc=min+(pocIdx+.5)*step,rank=profile.map((v,i)=>({v,i})).sort((a,b)=>b.v-a.v),hvn=rank.slice(0,3).map(x=>min+(x.i+.5)*step),lvn=rank.slice(-3).map(x=>min+(x.i+.5)*step),entry=bias==='SHORT'?[vah-a*.2,vah+a*.2]:[val-a*.2,val+a*.2] as [number,number],stop=bias==='SHORT'?vah+a*1.35:val-a*1.35,target=bias==='SHORT'?Math.min(...recent.filter(p=>p.kind==='low').map(p=>p.price),last-a*3):Math.max(...recent.filter(p=>p.kind==='high').map(p=>p.price),last+a*3),risk=Math.abs(avg(entry)-stop),rr=risk?Math.abs(target-avg(entry))/risk:0,location=bias==='LONG'?(last>=val&&last<=poc):(last<=vah&&last>=poc),score=Math.max(35,Math.min(94,50+(bull-bear)*(bias==='SHORT'?-5:5)+(location?12:0)+(rr>=2?10:0)));return{score:Math.round(score),bias,atr:a,pivots:ps,poc,vah,val,hvn,lvn,profile,profileStart:start,entry,stop,target,rr,snapshots:{'1D':snap(resample(data,26)),'4H':snap(resample(data,16)),'1H':snap(resample(data,4)),'15m':snap(data)},confidence:Math.min(95,55+Math.round(data.length/8))}}
export function backtest(data:Candle[],minRR=2,lookback=20):Backtest{let cash=10000,peak=cash,maxDD=0,wins=0,lossSum=0,winSum=0,trades=0,position:null|{entry:number;stop:number;target:number;risk:number;size:number}=null;const curve=[cash];for(let i=Math.max(lookback,20);i<data.length;i++){const c=data[i],a=atr(data.slice(0,i+1));if(position){let pnl:number|undefined;if(c.low<=position.stop)pnl=(position.stop-position.entry)*position.size;else if(c.high>=position.target)pnl=(position.target-position.entry)*position.size;if(pnl!==undefined){cash+=pnl;trades++;if(pnl>0){wins++;winSum+=pnl}else lossSum+=Math.abs(pnl);position=null}}if(!position){const high=Math.max(...data.slice(i-lookback,i).map(x=>x.high)),sma=avg(data.slice(i-20,i).map(x=>x.close));if(c.close>high&&c.close>sma&&a>0){const stop=c.close-a*1.5,risk=c.close-stop,size=(cash*.01)/risk;position={entry:c.close,stop,target:c.close+risk*minRR,risk,size}}}peak=Math.max(peak,cash);maxDD=Math.min(maxDD,(cash-peak)/peak*100);curve.push(cash)}const bh=(data.at(-1)!.close/data[0].close-1)*100;return{trades,wins,winRate:trades?wins/trades*100:0,returnPct:(cash/10000-1)*100,maxDrawdown:maxDD,profitFactor:lossSum?winSum/lossSum:winSum?99:0,avgRR:trades?(wins*minRR-(trades-wins))/trades:0,equity:curve,buyHold:bh}}
