import test from 'node:test';
import assert from 'node:assert/strict';
import {newTelemetry,observe,finishTelemetry} from './scan-telemetry.mjs';
const sample={availableMiB:220,freeBytes:8*1024**3,load:0.3};
const done={elapsedMs:50000,cpuMs:1000,status:'complete'};
test('no observations cannot report headroom',()=>assert.equal(finishTelemetry(newTelemetry(),done).state,'unknown'));
test('complete clean scan with conservative reserve reports observed headroom',()=>{const t=newTelemetry();observe(t,sample);assert.equal(finishTelemetry(t,done).state,'headroom');});
test('worst sample survives subsequent recovery',()=>{const t=newTelemetry();observe(t,{...sample,availableMiB:150,load:1});observe(t,sample);assert.equal(t.minAvailableMiB,150);assert.equal(t.maxLoad,1);assert.equal(finishTelemetry(t,done).state,'caution');});
test('failed requests, slow runs and incomplete coverage never suggest expansion',()=>{for(const extra of [{failedRequests:1}]){const t=newTelemetry();observe(t,sample);Object.assign(t,extra);assert.equal(finishTelemetry(t,done).state,'caution');}for(const x of [{status:'partial'},{status:'no_session'},{elapsedMs:600000}]){const t=newTelemetry();observe(t,sample);assert.equal(finishTelemetry(t,{...done,...x}).state,'caution');}});
test('earlier resource protection cannot be erased by a successful retry',()=>{const t=newTelemetry({state:'protected'});observe(t,sample);assert.equal(finishTelemetry(t,done).state,'protected');assert.equal(finishTelemetry(newTelemetry(),{...done,status:'resource_paused'}).state,'protected');});
