// Explicit bounded coverage, not a claim of screening every listed company.
export const LIMITS = Object.freeze({universe:25, detailed:6, minutes:15, reports:28, storageBytes:8*1024*1024, minAvailableMiB:128});
const kr=[['005930','삼성전자'],['000660','SK하이닉스'],['373220','LG에너지솔루션'],['207940','삼성바이오로직스'],['005380','현대차'],['000270','기아'],['068270','셀트리온'],['105560','KB금융'],['055550','신한지주'],['035420','NAVER'],['035720','카카오'],['012330','현대모비스'],['005490','POSCO홀딩스'],['028260','삼성물산'],['051910','LG화학'],['006400','삼성SDI'],['009540','HD한국조선해양'],['012450','한화에어로스페이스'],['329180','HD현대중공업'],['086790','하나금융지주'],['042700','한미반도체'],['058470','리노공업'],['196170','알테오젠'],['247540','에코프로비엠'],['145020','휴젤']];
const us=[['AAPL','Apple','ND'],['MSFT','Microsoft','ND'],['NVDA','NVIDIA','ND'],['AMZN','Amazon','ND'],['GOOGL','Alphabet','ND'],['META','Meta','ND'],['TSLA','Tesla','ND'],['AVGO','Broadcom','ND'],['AMD','AMD','ND'],['NFLX','Netflix','ND'],['COST','Costco','ND'],['ADBE','Adobe','ND'],['PLTR','Palantir','ND'],['JPM','JPMorgan','NY'],['V','Visa','NY'],['WMT','Walmart','ND'],['XOM','Exxon Mobil','NY'],['UNH','UnitedHealth','NY'],['JNJ','Johnson & Johnson','NY'],['ONDS','Ondas','ND'],['CRWD','CrowdStrike','ND'],['DDOG','Datadog','ND'],['ARM','Arm','ND'],['PANW','Palo Alto Networks','ND'],['MU','Micron','ND']];
export const UNIVERSE={KR:kr.map(([symbol,name])=>({market:'KR',symbol,name})),US:us.map(([symbol,name,exchange])=>({market:'US',symbol,name,exchange}))};
export function localParts(at,market){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:market==='KR'?'Asia/Seoul':'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23',weekday:'short'}).formatToParts(new Date(at)).map(p=>[p.type,p.value]));return {date:`${p.year}-${p.month}-${p.day}`,minute:+p.hour*60+(+p.minute),weekday:p.weekday};}
// NYSE published early closes. Unlisted/exceptional sessions are held until the usual close.
const earlyUS=new Set(['2026-11-27','2026-12-24','2027-11-26']);
export function closingMinute(market,date){return market==='KR'?930:earlyUS.has(date)?780:960;}
export function dueSession(market,at=Date.now()) {const p=localParts(at,market),close=closingMinute(market,p.date);if(['Sat','Sun'].includes(p.weekday)||p.minute<close+10||p.minute>close+70)return null;return {...p,close,closeAt:at-(p.minute-close)*60000-(at%60000)};}
export function resourceSafe({availableMiB,freeBytes,load}){return availableMiB>=LIMITS.minAvailableMiB&&freeBytes>2*1024**3&&load<1.5;}
export function beforeClose(bars,market,date,close){return bars.filter(b=>{const p=localParts(Date.parse(b.date),market);return p.date<date||(p.date===date&&p.minute<close);});}
