import test from 'node:test';import assert from 'node:assert/strict';import {composeTradePlan} from './trade-plan.ts';
const base={direction:'LONG',entryFrame:'1m',stage:'조건 확인',ready:true,interest:{low:90,high:110,at:1,id:'h4'},refined:{low:99,high:101,at:2,id:'m1'},risk:{stop:95,target:120},netR:3,asOf:3};
test('waiting plan never turns parent midpoint into entry or displays execution prices',()=>{const p=composeTradePlan({...base,ready:false});assert.deepEqual(p.interest,[90,110]);assert.equal(p.entry,undefined);assert.equal(p.stop,undefined);assert.equal(p.target,undefined)});
test('opposite target and inverted stop invalidate even a ready input',()=>{for(const risk of [{stop:95,target:80},{stop:105,target:120},{stop:NaN,target:120}])assert.equal(composeTradePlan({...base,risk}).ready,false)});
test('long and short plans retain coherent ordered prices and chosen timeframe',()=>{const long=composeTradePlan(base);assert.ok(long.ready);assert.deepEqual(long.entry,[99,101]);const short=composeTradePlan({...base,direction:'SHORT',entryFrame:'5m',risk:{stop:105,target:80}});assert.ok(short.ready);assert.equal(short.entryFrame,'5m');assert.ok(short.target<short.entry[0]&&short.stop>short.entry[1])});
test('missing refinement and inadequate net reward remain waiting',()=>{assert.equal(composeTradePlan({...base,refined:undefined}).ready,false);assert.equal(composeTradePlan({...base,netR:1.9}).entry,undefined)});
test('parent risk appears before entry approval without exposing executable prices',()=>{const p=composeTradePlan({...base,ready:false,refined:undefined});assert.equal(p.ready,false);assert.deepEqual(p.candidate,{stop:95,target:120});assert.equal(p.entry,undefined);assert.equal(p.stop,undefined)});
test('refinement changes the candidate entry but never parent stop or target',()=>{const a=composeTradePlan({...base,ready:false});const b=composeTradePlan({...base,ready:false,entryFrame:'5m',refined:{low:100,high:102,at:2,id:'m5'}});assert.deepEqual(a.candidate.entry,[99,101]);assert.deepEqual(b.candidate.entry,[100,102]);assert.equal(a.candidate.stop,b.candidate.stop);assert.equal(a.candidate.target,b.candidate.target)});
test('invalid parent targets are not displayed as pending plans',()=>{assert.equal(composeTradePlan({...base,ready:false,risk:{stop:95,target:80}}).candidate,undefined)});
